


export const SET_CURRENT_AVATAR: string = "ACTIONS/SET/CURRENT_AVATAR"
export const GET_CURRENT_AVATAR: string = "ACTIONS/GET/CURRENT_AVATAR"
export const LOGOUT: string = "ACTIONS/LOGOUT"

export const ADD_METALINK_TO_AVATAR = "ACTIONS/ADD/METALINK"